lr: 0.001
min_lr: 0.000001
weight_decay: 0.00001
es_patience: 6


embedding_dim: 64

d_model: 64

Encoder:
  N_layer: 1
  nhead: 2
  inner_dim: 256
  dropout: 0.2

Decoder:
  N_layer: 1
  nhead: 2
  inner_dim: 256
  dropout: 0.2


decoder_index:
  vocab_size: 10
  embedding_dim: 64
  tree_nodes_num: 4863
  max_len: 6

rk_weight: 0.05

rk_num_neg: 4
rk_margin: 0.001

rk_act : 'sigmoid'

sm_temp: 0.2
sm_weight: 0.09
